apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mylocalstorage
  hostPath:
    path: /mnt/f
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  resources:
    requests:
      storage: 20Gi
  storageClassName: mylocalstorage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

